[package]
name = "cloner"
version = "0.1.0"
authors = ["Jack Michaud <jack@lomz.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
git-url-parse = "0.3.1"
